# Pipeline name convention
name: '$(Build.SourceBranchName)$(System.PullRequest.SourceBranch)$(Rev:.r)'

# Trigger configuration
trigger:
  - main
  - feature/*
  - release/*

pr:
  - main
  - releases/*

# Parameters
parameters:
  - name: prDeployment
    type: boolean
    default: true
  - name: branchDeployment
    type: boolean
    default: true
  - name: sndDeployment
    type: boolean
    default: true

# Resources
resources:
  repositories:
    - repository: templates
      endpoint: DEFRA
      type: github
      name: defra/fcp-pipeline-common
      # ref: pl-709   # Optional: build with a specific pipeline version

# Pipeline template
extends:
  template: fcp-common-pipeline.yaml@templates
  parameters:
    appFrameworkType: nodejs   # Optional: nodejs (default), dotnet, java
    Type: kubernetes           # Optional: kubernetes (default), npm, functions, nuget
    npmLegacyPeerDeps: false   # Optional: default is false
    dockerFilePath: Dockerfile # Optional default is Dockerfile
    prDeployment: ${{ parameters.prDeployment }}
    branchDeployment: ${{ parameters.branchDeployment }}
    sndDeployment: ${{ parameters.sndDeployment }}
    # failOnThreshold: moderate
    variableGroupName: ffc-pay-responses-env-var
    pr_params:
      processingActive: ${{ eq(variables['pr_processingActive'], 'true') }}
    snd2_params:
      processingActive: ${{ eq(variables['snd2_processingActive'], 'true') }}
    dev_params:
      processingActive: ${{ eq(variables['dev_processingActive'], 'true') }}
    test_params:
      processingActive: ${{ eq(variables['test_processingActive'], 'true') }}
    pre_params:
      processingActive: ${{ eq(variables['pre_processingActive'], 'true') }}
    prd_params:
      processingActive: ${{ eq(variables['prd_processingActive'], 'true') }}
