version: '3.8'

services:
  ffc-sfi-payment-responses:
    build:
      context: .
      target: production
    image: ffc-sfi-payment-responses
    container_name: ffc-sfi-payment-responses
    environment:
      APPINSIGHTS_CLOUDROLE: ffc-sfi-payment-responses-local
      APPINSIGHTS_INSTRUMENTATIONKEY: ${APPINSIGHTS_INSTRUMENTATIONKEY}
