# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ffc-pay-responses:
    build:
      target: development
    image: ffc-pay-responses-development
    container_name: ffc-pay-responses-development
    ports:
      - "3012:3012"
      - "9244:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
    environment:
      AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://ffc-pay-responses-azurite:10000/devstoreaccount1;
    depends_on:
      - ffc-pay-responses-azurite
      
  ffc-pay-responses-postgres:
    ports:
      - "5420:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ffc-pay-responses-azurite:
    volumes:
      - azurite_data:/data
    ports:
      - "10002:10000"

volumes:
  azurite_data:
  postgres_data:
