environment: production
environmentCode:
name: ffc-pay-responses
namespace: ffc-pay
image: ffc-pay-responses

labels:
  component: service

appInsights:
  key:

containerConfigMap:
  name: ffc-pay-responses-config-map

containerSecret:
  name: ffc-pay-responses-container-secret
  type: Opaque

deployment:

container:
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 180Mi
  limitCpu: 120m
  messageQueueHost: namespace.servicebus.windows.net
  acknowledgementTopicAddress: ffc-pay-acknowledgement
  returnTopicAddress: ffc-pay-return
  eventTopicAddress: ffc-pay-event
  azureStorageAccountName: ffcpay
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false  
  azureStorageCreateContainers: false
  storageContainer: dax
  inboundFolder: inbound
  archiveFolder: archive
  quarantineFolder: quarantine

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
