environment: development
name: ffc-pay-responses
namespace: ffc-pay
workstream: ffc-pay
image: ffc-pay-responses

labels:
  component: service

appInsights:
  key:

containerConfigMap:
  name: ffc-pay-responses-config-map

containerSecret:
  name: ffc-pay-responses-container-secret
  type: Opaque

deployment:
  restartPolicy: Always
  priorityClassName: default
  replicas: 1
  minReadySeconds: 0

container:
  imagePullPolicy: IfNotPresent
  requestMemory: 10Mi
  requestCpu: 10m
  limitMemory: 180Mi
  limitCpu: 120m
  messageQueueHost: namespace.servicebus.windows.net
  acknowledgementTopicAddress: ffc-pay-acknowledgement
  returnTopicAddress: ffc-pay-return
  azureStorageAccountName: payments
  azureStorageConnectionString: dummy
  azureStorageUseConnectionString: false
  inboundContainer: payment-responses-inbound
  archiveContainer: payment-responses-archive
  quarantineContainer: payment-responses-quarantine

aadPodIdentity: true

azureIdentity:
  clientID: not-a-real-clientID
  resourceID: not-a-real-resourceID
