apiVersion: v2
description: FFC SFI payment response processing
name: ffc-sfi-payment-responses
# this version is automatically updated in the build pipline
version: 1.0.0
dependencies:
- name: ffc-helm-library
  version: ^2.11.0
  repository: https://raw.githubusercontent.com/defra/ffc-helm-repository/master/
